# server
server:
  port: 9090
  servlet:
    context-path: /road_examination_manager

# mybatis
mybatis:
  mapper-locations: classpath:mappers/*.xml

spring:
  #开启热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/road_examination?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
