# spring datasource
spring.datasource.url=jdbc:mysql://localhost:3306/road_examination?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=123456
# server
server.port=9090
server.servlet.context-path=/road_examination_manager

# mybatis
mybatis.mapper-locations=classpath:mappers/*.xml

# 这里现在热部署没有用
#开启热部署
spring.devtools.restart.enabled=true
#设置重启的目录
spring.devtools.restart.additional-paths=src/main/java
#设置文件修改不重启，相对于classpath
spring.devtools.restart.exclude=WEB-INF/**

# templates
spring.thymeleaf.prefix=classpath:/static/web/manager/
spring.thymeleaf.suffix=.html

#开发时关闭缓存,不然没法看到实时页面
spring.thymeleaf.cache=false
